fix: false              # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 2.5       # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'vendor/**/*'
