# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby-vips8 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby-vips8"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["John Cupitt"]
  s.date = "2016-01-25"
  s.description = "ruby-vips8 is a ruby extension for vips8. It is extremely fast and it can process huge images without requiring the entire image to be loaded into memory."
  s.email = "jcupitt@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "TODO"
  ]
  s.files = [
    ".rspec",
    ".yardopts",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO",
    "VERSION",
    "example/annotate.rb",
    "example/daltonize8.rb",
    "example/example1.rb",
    "example/example2.rb",
    "example/example3.rb",
    "example/example4.rb",
    "example/example5.rb",
    "example/trim8.rb",
    "example/watermark.rb",
    "example/wobble.rb",
    "lib/vips8.rb",
    "lib/vips8/access.rb",
    "lib/vips8/align.rb",
    "lib/vips8/angle.rb",
    "lib/vips8/angle45.rb",
    "lib/vips8/argument.rb",
    "lib/vips8/bandformat.rb",
    "lib/vips8/call.rb",
    "lib/vips8/coding.rb",
    "lib/vips8/demandstyle.rb",
    "lib/vips8/direction.rb",
    "lib/vips8/error.rb",
    "lib/vips8/extend.rb",
    "lib/vips8/foreignflags.rb",
    "lib/vips8/image.rb",
    "lib/vips8/interpolate.rb",
    "lib/vips8/interpretation.rb",
    "lib/vips8/methods.rb",
    "lib/vips8/operation.rb",
    "ruby-vips8.gemspec",
    "spec/image_spec.rb",
    "spec/samples/balloon.v",
    "spec/samples/ghost.ppm",
    "spec/samples/huge.jpg",
    "spec/samples/icc.jpg",
    "spec/samples/lcd.icc",
    "spec/samples/lion.svg",
    "spec/samples/sample.csv",
    "spec/samples/sample.exr",
    "spec/samples/wagon.jpg",
    "spec/samples/wagon.v",
    "spec/spec_helper.rb",
    "spec/vips_spec.rb"
  ]
  s.homepage = "http://github.com/jcupitt/ruby-vips8"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Ruby extension for the vips8 image processing library."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gobject-introspection>, ["~> 3.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<redcarpet>, ["~> 3.3"])
      s.add_development_dependency(%q<github-markup>, ["~> 1.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
    else
      s.add_dependency(%q<gobject-introspection>, ["~> 3.0"])
      s.add_dependency(%q<rspec>, ["~> 3.3"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<redcarpet>, ["~> 3.3"])
      s.add_dependency(%q<github-markup>, ["~> 1.4"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<gobject-introspection>, ["~> 3.0"])
    s.add_dependency(%q<rspec>, ["~> 3.3"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<redcarpet>, ["~> 3.3"])
    s.add_dependency(%q<github-markup>, ["~> 1.4"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
  end
end

