VALUE img_lab_to_lch(VALUE);
VALUE img_lch_to_lab(VALUE);
VALUE img_labq_to_xyz(VALUE);
VALUE img_rad_to_float(VALUE);
VALUE img_float_to_rad(VALUE);
VALUE img_lch_to_ucs(VALUE);
VALUE img_lab_to_labq(VALUE);
VALUE img_lab_to_labs(VALUE);
VALUE img_lab_to_xyz(VALUE);
VALUE img_lab_to_xyz_temp(VALUE, VALUE, VALUE, VALUE);
VALUE img_lab_to_ucs(VALUE);
VALUE img_labq_to_lab(VALUE);
VALUE img_labq_to_labs(VALUE);
VALUE img_labs_to_labq(VALUE);
VALUE img_labs_to_lab(VALUE);
VALUE img_ucs_to_xyz(VALUE);
VALUE img_ucs_to_lch(VALUE);
VALUE img_ucs_to_lab(VALUE);
VALUE img_xyz_to_lab(VALUE);
VALUE img_xyz_to_lab_temp(VALUE, VALUE, VALUE, VALUE);
VALUE img_xyz_to_ucs(VALUE);
VALUE img_srgb_to_xyz(VALUE);
VALUE img_xyz_to_srgb(VALUE);
VALUE img_yxy_to_xyz(VALUE);
VALUE img_xyz_to_yxy(VALUE);
VALUE img_decmc_from_lab(VALUE, VALUE);
VALUE img_de00_from_lab(VALUE, VALUE);
VALUE img_de_from_xyz(VALUE, VALUE);
VALUE img_de_from_lab(VALUE, VALUE);
VALUE img_lab_morph(VALUE, VALUE, VALUE, VALUE, VALUE, VALUE);
VALUE img_icc_transform(VALUE, VALUE, VALUE, VALUE);
VALUE img_icc_import(VALUE, VALUE, VALUE);
VALUE img_icc_import_embedded(VALUE, VALUE);
VALUE img_icc_export_depth(VALUE, VALUE, VALUE, VALUE);
VALUE img_icc_ac2rc(VALUE, VALUE, VALUE);
void init_Image_colour();
