VALUE img_conv(VALUE, VALUE);
VALUE img_convsep(VALUE, VALUE);
VALUE img_compass(VALUE, VALUE);
VALUE img_gradient(VALUE, VALUE);
VALUE img_lindetect(VALUE, VALUE);
VALUE img_sharpen(VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE);
VALUE img_grad_x(VALUE);
VALUE img_grad_y(VALUE);
VALUE img_fastcor(VALUE, VALUE);
VALUE img_spcor(VALUE, VALUE);
VALUE img_gradcor(VALUE, VALUE);
VALUE img_contrast_surface(VALUE, VALUE, VALUE);
VALUE img_addgnoise(VALUE, VALUE);
