VALUE img_lrmerge(int, VALUE*, VALUE);
VALUE img_tbmerge(int, VALUE*, VALUE);
VALUE img_lrmerge1(int, VALUE*, VALUE);
VALUE img_tbmerge1(int, VALUE*, VALUE);
VALUE img_lrmosaic(int, VALUE*, VALUE);
VALUE img_tbmosaic(int, VALUE*, VALUE);
VALUE img_lrmosaic1(int, VALUE*, VALUE);
VALUE img_tbmosaic1(int, VALUE*, VALUE);
VALUE img_global_balance(VALUE, VALUE);
VALUE img_global_balancef(VALUE, VALUE);
VALUE img_correl(VALUE, VALUE, VALUE, VALUE, VALUE,	VALUE, VALUE, VALUE);
VALUE img_remosaic(VALUE, VALUE, VALUE);
VALUE img_align_bands(VALUE);
VALUE img_maxpos_subpel(VALUE);
void init_Image_mosaicing(void);
