VALUE img_to_mask(VALUE);
VALUE img_dup(VALUE);
VALUE img_copy_swap(VALUE);
VALUE img_copy_native(VALUE, VALUE);
VALUE img_copy_file(VALUE);
VALUE img_clip2fmt(VALUE, VALUE);
VALUE img_scale(VALUE);
VALUE img_msb(int, VALUE*, VALUE);
VALUE img_c2amph(VALUE);
VALUE img_c2rect(VALUE);
VALUE img_ri2c(VALUE, VALUE);
VALUE img_c2imag(VALUE);
VALUE img_c2real(VALUE);
VALUE img_scaleps(VALUE);
VALUE img_falsecolour(VALUE);
VALUE img_s_gaussnoise(VALUE, VALUE, VALUE, VALUE, VALUE);
VALUE img_s_black(VALUE, VALUE, VALUE, VALUE);
VALUE img_s_text(VALUE, VALUE, VALUE, VALUE, VALUE, VALUE);
VALUE img_extract_band(int, VALUE*, VALUE);
VALUE img_extract_area(int, VALUE*, VALUE);
VALUE img_embed(VALUE, VALUE, VALUE, VALUE, VALUE, VALUE);
VALUE img_bandjoin(int, VALUE *argv, VALUE);
VALUE img_insert_noexpand(VALUE, VALUE, VALUE, VALUE);
VALUE img_insert(int, VALUE *argv, VALUE);
VALUE img_lrjoin(VALUE, VALUE);
VALUE img_tbjoin(VALUE, VALUE);
VALUE img_replicate(VALUE, VALUE, VALUE);
VALUE img_grid(VALUE, VALUE, VALUE, VALUE);
VALUE img_wrap(VALUE, VALUE, VALUE);
VALUE img_fliphor(VALUE);
VALUE img_flipver(VALUE);
VALUE img_rot90(VALUE);
VALUE img_rot180(VALUE);
VALUE img_rot270(VALUE);
VALUE img_subsample(int, VALUE*, VALUE);
VALUE img_zoom(int, VALUE*, VALUE);
void init_Image_conversion();