VALUE img_dilate(VALUE, VALUE);
VALUE img_erode(VALUE, VALUE);
VALUE img_rank(VALUE, VALUE, VALUE, VALUE);
VALUE img_rank_image_internal(int, VALUE*, VALUE, int);
VALUE img_rank_image(int, VALUE*, VALUE);
VALUE img_maxvalue(int, VALUE*, VALUE);
VALUE img_cntlines_h(VALUE);
VALUE img_cntlines_v(VALUE);
VALUE img_zerox_pos(VALUE);
VALUE img_zerox_neg(VALUE);
VALUE img_profile_h(VALUE);
VALUE img_profile_v(VALUE);
VALUE img_label_regions(VALUE);
