VALUE img_measure_area(VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE, VALUE);
VALUE img_stats(VALUE);
VALUE img_max(VALUE);
VALUE img_min(VALUE);
VALUE img_avg(VALUE);
VALUE img_deviate(VALUE);
VALUE img_maxpos_avg(VALUE);
VALUE img_maxpos(int, VALUE*, VALUE);
VALUE img_minpos(int, VALUE*, VALUE);
VALUE img_bandmean(VALUE);
VALUE img_add(VALUE, VALUE);
VALUE img_subtract(VALUE, VALUE);
VALUE img_invert(VALUE);
VALUE img_lin(VALUE, VALUE, VALUE);
VALUE img_multiply(VALUE, VALUE);
VALUE img_remainder(int, VALUE*, VALUE);
VALUE img_remainder_binop(VALUE, VALUE);
VALUE img_divide(VALUE, VALUE);
VALUE img_recomb(VALUE, VALUE);
VALUE img_sign(VALUE);
VALUE img_abs(VALUE);
VALUE img_floor(VALUE);
VALUE img_rint(VALUE);
VALUE img_ceil(VALUE);
VALUE img_s_linreg(int, VALUE*, VALUE);
VALUE img_point(VALUE, VALUE, VALUE, VALUE, VALUE);
VALUE img_pow(int, VALUE*, VALUE);
VALUE img_pow_binop(int, VALUE*, VALUE);
VALUE img_expn(int, VALUE*, VALUE);
VALUE img_log(VALUE);
VALUE img_log10(VALUE);
VALUE img_sin(VALUE);
VALUE img_asin(VALUE);
VALUE img_cos(VALUE);
VALUE img_acos(VALUE);
VALUE img_tan(VALUE);
VALUE img_atan(VALUE);
VALUE img_cross_phase(VALUE, VALUE);
